# Generated by Django 6.0 on 2026-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('ACTIVATED', 'Activated')], default='CREATED', max_length=20),
        ),
    ]
