# Book related constants

MAX_TITLE_LENGTH = 255
MIN_TITLE_LENGTH = 1
MAX_AUTHOR_LENGTH = 255
MIN_AUTHOR_LENGTH = 1
MAX_ISBN_LENGTH = 13
MIN_ISBN_LENGTH = 10

# Genre constants
MAX_GENRE_NAME_LENGTH = 100

# Status/Visibility constants
MAX_STATUS_LENGTH = 20
MAX_VISIBILITY_LENGTH = 10

# Premium Limits
FREE_PLAN_BOOK_LIMIT = 5
