# Generated by Django 6.0 on 2026-01-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
