# Generated by Django 6.0 on 2026-01-11 10:04

import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        code="invalid_author",
                        message="Author must start with a letter and may contain letters, numbers, spaces, dots, hyphens, or apostrophes.",
                        regex="^[A-Za-z][A-Za-z0-9 .'-]*$",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(10),
                    common.validators.isbn_validator,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_year",
            field=models.SmallIntegerField(
                default=2000, validators=[common.validators.published_year_validator]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        code="invalid_title",
                        message="Title can only contain letters, numbers, spaces, and common punctuation (@, #, &, etc.).",
                        regex="^[a-zA-Z0-9\\s_'.,:;!?()@#&-]+$",
                    ),
                ],
            ),
        ),
    ]
