# Generated by Django 6.0 on 2026-01-17 15:02

from django.db import migrations


def assign_default_tenant(apps, schema_editor):
    """
    Create a default tenant and assign all existing books/genres to it.
    This handles existing data before making tenant field non-nullable.
    """
    Tenant = apps.get_model('tenants', 'Tenant')
    Book = apps.get_model('books', 'Book')
    Genre = apps.get_model('books', 'Genre')

    # Create or get default tenant
    default_tenant, created = Tenant.objects.get_or_create(
        slug='default',
        defaults={
            'name': 'Default Tenant',
            'is_active': True,
            'subscription_plan': 'FREE',
        }
    )

    # Assign all books without tenant to default tenant
    Book.objects.filter(tenant__isnull=True).update(tenant=default_tenant)

    # Assign all genres without tenant to default tenant
    Genre.objects.filter(tenant__isnull=True).update(tenant=default_tenant)


def reverse_assign_default_tenant(apps, schema_editor):
    """
    Reverse: Set tenant to NULL (for rollback)
    """
    Book = apps.get_model('books', 'Book')
    Genre = apps.get_model('books', 'Genre')
    Tenant = apps.get_model('tenants', 'Tenant')

    try:
        default_tenant = Tenant.objects.get(slug='default')
        Book.objects.filter(tenant=default_tenant).update(tenant=None)
        Genre.objects.filter(tenant=default_tenant).update(tenant=None)
    except Tenant.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_tenant_genre_tenant_alter_book_deleted_at_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            assign_default_tenant,
            reverse_assign_default_tenant,
        ),
    ]
