# Generated by Django 6.0 on 2026-01-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
    ]
