# Generated by Django 6.0 on 2026-01-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_table'),
    ]

    operations = [
     
        migrations.RunSQL(
            sql="ALTER TABLE user_groups RENAME COLUMN users_id TO user_id;",
            reverse_sql="ALTER TABLE user_groups RENAME COLUMN user_id TO users_id;",
        ),
        
        migrations.RunSQL(
            sql="ALTER TABLE user_user_permissions RENAME COLUMN users_id TO user_id;",
            reverse_sql="ALTER TABLE user_user_permissions RENAME COLUMN user_id TO users_id;",
        ),
    ]
