# Generated by Django 6.0 on 2026-01-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                BEGIN 
                    ALTER TABLE user_groups RENAME COLUMN users_id TO user_id; 
                EXCEPTION 
                    WHEN undefined_column THEN 
                        NULL; 
                END; 
            END $$;
            """,
            reverse_sql="""
            DO $$ 
            BEGIN 
                BEGIN 
                    ALTER TABLE user_groups RENAME COLUMN user_id TO users_id; 
                EXCEPTION 
                    WHEN undefined_column THEN 
                        NULL; 
                END; 
            END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN 
                BEGIN 
                    ALTER TABLE user_user_permissions RENAME COLUMN users_id TO user_id; 
                EXCEPTION 
                    WHEN undefined_column THEN 
                        NULL; 
                END; 
            END $$;
            """,
            reverse_sql="""
            DO $$ 
            BEGIN 
                BEGIN 
                    ALTER TABLE user_user_permissions RENAME COLUMN user_id TO users_id; 
                EXCEPTION 
                    WHEN undefined_column THEN 
                        NULL; 
                END; 
            END $$;
            """,
        ),
    ]
