# Generated by Django 6.0 on 2026-01-21 17:07

import common.managers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_fix_m2m_columns"),
        ("tenants", "0002_alter_tenant_deleted_at_alter_tenant_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", common.managers.TenantAwareUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(3),
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Username must start with a small letter and can only contain small letters, numbers, underscores, dots, or hyphens.",
                        regex="^[a-zA-Z][a-zA-Z0-9_.-]*$",
                    ),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("email", "tenant")},
        ),
    ]
