MIN_PASSWORD_LENGTH = 8

MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH =30 
MAX_PHONE_LENGTH=13
MAX_ROLE_LENGTH=10
MAX_MAX_LENGTH=50

# Book constants
MAX_TITLE_LENGTH = 255
MIN_TITLE_LENGTH = 1
MAX_AUTHOR_LENGTH = 255
MIN_AUTHOR_LENGTH = 1
MAX_ISBN_LENGTH = 13
MIN_ISBN_LENGTH = 10
MIN_PUBLISHED_YEAR = 1000

# Genre constants
MAX_GENRE_NAME_LENGTH = 100

# Status/Visibility constants
MAX_STATUS_LENGTH = 20
MAX_VISIBILITY_LENGTH = 10
