
THROTTLE_RATE_ANON = "1000/hour"
THROTTLE_RATE_USER = "1000/hour"
THROTTLE_RATE_IP = "100/minute"
THROTTLE_RATE_AUTH = "10/minute"


CELERY_MAX_RETRIES = 3
CELERY_COUNTDOWN_SHORT = 10     
CELERY_COUNTDOWN_LONG = 60      


SECONDS_IN_DAY = 60 * 60 * 24
TENANT_SEED_CACHE_TTL = SECONDS_IN_DAY * 7   


DEFAULT_OTP_EXPIRY_MINUTES = 15
DEFAULT_USER_DATA_RETENTION_DAYS = 30
DEFAULT_UNVERIFIED_USER_CLEANUP_HOURS = 24
